# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane
default_platform(:ios)

platform :ios do

  desc "Push a new beta build to TestFlight"
  lane :beta do
    increment_build_number

    build_app(project: "HomeIndicator.xcodeproj",
     scheme: "HomeIndicator WatchKit App",
     destination: "generic/platform=watchOS",
     xcargs: "-allowProvisioningUpdates"
    )

    upload_to_testflight(
      username: ENV["EMAILADDRESS"]
    )
  end

  lane :beta_ci do
    # 1. Keychainの準備
    setup_ci(provider: "travis")
  
    # 2. AppStoreConenct APIの準備
    api_key = app_store_connect_api_key(
      key_id: ENV["ASC_KEY_ID"],
      issuer_id: ENV["ASC_ISSUER_ID"],
      key_content: ENV["ASC_KEY_CONTENT"],
      in_house: false
    )
  
    # 3. GitHubアクセスの準備
    username = ENV["USERNAME"]
    personal_github_access_token = ENV["PERSONAL_GITHUB_ACCESS_TOKEN"]
    authorization_token_str = "#{username}:#{personal_github_access_token}"
    basic_authorization_token = Base64.strict_encode64(authorization_token_str)
  
    # 4. fastlane matchを使って証明書をインストール
    match(
      git_basic_authorization: basic_authorization_token,
      api_key: api_key,
      app_identifier: [
        "com.Shitamori.HomeIndicator",
        "com.Shitamori.HomeIndicator.watchkitapp",
        "com.Shitamori.HomeIndicator.watchkitapp.watchkitextension"
      ],
      type: "appstore",
      readonly: is_ci
    )
  
    # ビルド番号をインクリメント
    increment_build_number
    commit_version_bump
    push_to_git_remote
  
    # アプリをビルド
    build_app(
      project: "HomeIndicator.xcodeproj",
      scheme: "HomeIndicator WatchKit App",
      destination: "generic/platform=watchOS",
      export_options: {
        method: "app-store",
      }
    )
  
    # 5. テストフライトで配布
    upload_to_testflight(
      api_key: api_key,
      skip_waiting_for_build_processing: true
    )
  end
end
